from django.db import models

import datetime
from django.utils import timezone

# Create your models here.
# Table names are automatically generated by combining the name 
# of the app (polls) and the lowercase name of the model 
# – question and choice. (You can override this behavior.)
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        # Make sure our custom method worked.
        # >>> q = Question.objects.get(pk=1)
        # >>> q.was_published_recently()

# Each Choice is associated with a Question (ForeignKey)
class Choice(models.Model):
    # Each model has a number of class variables, 
    # each of which represents a database field in the model
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    # The different model field types (DateTimeField, CharField, IntegerField) 
    # correspond to the appropriate HTML input widget

    def __str__(self):
        return self.choice_text